const curiosities = {
  Brazil: "No Brasil, é ilegal dirigir usando chinelos.",
  Canada: "No Canadá, é ilegal pagar com mais de 25 moedas de 1 centavo.",
  Japan: "No Japão, dormir no trabalho pode ser sinal de dedicação.",
  Australia: "Na Austrália, é ilegal andar com mais de 50 kg de batatas se for produtor licenciado.",
  France: "Na França, é ilegal nomear um porco de Napoleão.",
  Germany: "Na Alemanha, é ilegal ficar sem combustível na Autobahn.",
  China: "Na China, existem mais de 1,3 bilhões de pessoas.",
  India: "Na Índia, o Holi é conhecido como o festival das cores.",
  Russia: "A Rússia é o maior país do mundo em área territorial.",
  Egypt: "No Egito, as pirâmides de Gizé são uma das Sete Maravilhas do Mundo Antigo.",
  Mexico: "O México é o berço do chocolate, que vem do cacau.",
  SouthAfrica: "A África do Sul tem três capitais diferentes.",
  Argentina: "A Argentina é famosa pelo tango e pela carne bovina.",
  Italy: "Na Itália, o Coliseu é um famoso anfiteatro romano.",
  Spain: "Na Espanha, a Tomatina é uma festa de guerra de tomates.",
  UnitedKingdom: "No Reino Unido, o chá da tarde é uma tradição clássica.",
  USA: "Os Estados Unidos têm o maior PIB do mundo.",
  SaudiArabia: "Na Arábia Saudita, a cidade de Meca é o local mais sagrado do Islã.",
  SouthKorea: "Na Coreia do Sul, o K-pop é um fenômeno mundial.",
  Turkey: "A Turquia é o único país que está em dois continentes: Europa e Ásia.",
  Greece: "A Grécia é o berço da democracia.",
  Norway: "Na Noruega, o sol da meia-noite brilha durante o verão.",
  Sweden: "Na Suécia, o conceito de ‘fika’ significa fazer uma pausa para café e bolo.",
  Netherlands: "Nos Países Baixos, existem mais bicicletas do que pessoas.",
  Portugal: "Portugal é conhecido pelos azulejos coloridos que decoram suas cidades.",
  Belgium: "A Bélgica é famosa pelo chocolate e pelas batatas fritas.",
  Indonesia: "A Indonésia é o maior arquipélago do mundo, com mais de 17 mil ilhas.",
  Thailand: "Na Tailândia, o festival Loi Krathong celebra a luz e a água.",
  Vietnam: "No Vietnã, o café é tradicionalmente servido com leite condensado.",
  Colombia: "A Colômbia é uma das maiores produtoras de café do mundo.",
  Chile: "O Deserto do Atacama, no Chile, é o mais seco do mundo.",
  Peru: "O Peru abriga a antiga cidade inca de Machu Picchu.",
  NewZealand: "A Nova Zelândia tem mais ovelhas do que pessoas.",
  Ireland: "Na Irlanda, o trevo é símbolo de sorte e tradição.",
  Poland: "A Polônia tem uma das maiores reservas de carvão da Europa.",
  CzechRepublic: "Praga, na República Tcheca, é conhecida como 'A Cidade das Cem Torres'.",
  Hungary: "A Hungria é famosa por seus banhos termais.",
  Finland: "Na Finlândia, existe uma forte tradição de saunas.",
  Malaysia: "Na Malásia, a Torre Petronas já foi o prédio mais alto do mundo.",
  Singapura: "Singapura é uma das cidades mais limpas e organizadas do mundo.",
};

export default curiosities;
